Esercizio_finale_s7/Esercizio_finale_s7/Controllers/OrdineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Esercizio_finale_s7.Models;


namespace Esercizio_finale_s7.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrdineController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Ordine
        public ActionResult Index()
        {
            var ordini = db.Ordine.Where(o => !o.IsDeleted).Include(o => o.Utente);
            return View(ordini.ToList());
        }

        // GET: Ordine/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            return View(ordine);
        }

        // GET: Ordine/Create
        public ActionResult Create()
        {
            ViewBag.IdUtente = new SelectList(db.Utente.Select(u => new
            {
                Id = u.IdUtente,
                NomeCompleto = u.Nome + " " + u.Cognome
            }), "Id", "NomeCompleto");

            return View(new Ordine());
        }


        // POST: Ordine/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdOrdine,IdUtente,DataOrdine,Importo,IndirizzoConsegna,NoteSpeciali,Evaso")] Ordine ordine)
        {
            if (ModelState.IsValid)
            {
                db.Ordine.Add(ordine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdUtente = new SelectList(db.Utente, "IdUtente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // GET: Ordine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdUtente = new SelectList(db.Utente, "IdUtente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // POST: Ordine/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdOrdine,IdUtente,DataOrdine,Importo,IndirizzoConsegna,NoteSpeciali,Evaso")] Ordine ordine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ordine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdUtente = new SelectList(db.Utente, "IdUtente", "Nome", ordine.IdUtente);
            return View(ordine);
        }

        // GET: Ordine/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            return View(ordine);
        }

        // POST: Ordine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ordine ordine = db.Ordine.Find(id);
            if (ordine == null)
            {
                return HttpNotFound();
            }
            ordine.IsDeleted = true;
            db.Entry(ordine).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpGet]
        public JsonResult GetTotaleOrdiniEvasi()
        {
            var totaleOrdiniEvasi = db.Ordine.Where(o => o.Evaso && !o.IsDeleted).Count();
            return Json(totaleOrdiniEvasi, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSommaImportiOrdiniEvasi(DateTime data)
        {
            DateTime inizioGiorno = data.Date;
            DateTime fineGiorno = data.Date.AddDays(1).AddTicks(-1);

            decimal sommaImporti = db.Ordine
                .Where(o => o.Evaso && !o.IsDeleted && o.DataOrdine >= inizioGiorno && o.DataOrdine <= fineGiorno)
                .Select(o => o.Importo)
                .DefaultIfEmpty(0)
                .Sum();

            return Json(sommaImporti, JsonRequestBehavior.AllowGet);
        }

    }
}

Esercizio_finale_s7/Esercizio_finale_s7/Controllers/ProdottoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Esercizio_finale_s7.Models;

namespace Esercizio_finale_s7.Controllers
{
    public class ProdottoController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Prodottoe
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var prodotti = db.Prodotto.Where(p => !p.IsDeleted).ToList();
            return View(prodotti);
        }

        // GET: Prodottoe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotto prodotto = db.Prodotto.Find(id);
            if (prodotto == null)
            {
                return HttpNotFound();
            }
            return View(prodotto);
        }

        // GET: Prodottoe/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View(new Prodotto());
        }

        // POST: Prodottoe/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "IdProdotto,Nome,Foto,Prezzo,TempoConsegna,Ingredienti")] Prodotto prodotto, HttpPostedFileBase Foto)
        {
            if (Foto != null && Foto.ContentLength > 0)
            {
                string nomeFile = Path.GetFileName(Foto.FileName);
                string pathToSave = Path.Combine(Server.MapPath("~/Content/Images/"), nomeFile);
                Foto.SaveAs(pathToSave);
                prodotto.Foto = nomeFile;
            }
            if (ModelState.IsValid)
            {
                db.Prodotto.Add(prodotto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(prodotto);
        }

        // GET: Prodottoe/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotto prodotto = db.Prodotto.Find(id);
            if (prodotto == null)
            {
                return HttpNotFound();
            }
            return View(prodotto);
        }

        // POST: Prodottoe/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "IdProdotto,Nome,Foto,Prezzo,TempoConsegna,Ingredienti")] Prodotto prodotto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prodotto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(prodotto);
        }

        // GET: Prodottoe/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotto prodotto = db.Prodotto.Find(id);
            if (prodotto == null)
            {
                return HttpNotFound();
            }
            return View(prodotto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Prodotto prodotto = db.Prodotto.Find(id);
            if (prodotto == null)
            {
                return HttpNotFound();
            }
            prodotto.IsDeleted = true;
            db.Entry(prodotto).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Esercizio_finale_s7/Esercizio_finale_s7/Controllers/UtenteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Esercizio_finale_s7.Models;

namespace Esercizio_finale_s7.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UtenteController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Utente
        public ActionResult Index()
        {
            var utentiAttivi = db.Utente.Where(u => !u.IsDeleted).Include(u => u.Ruolo);
            return View(utentiAttivi.ToList());
        }

        // GET: Utente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            return View(utente);
        }

        // GET: Utente/Create
        public ActionResult Create()
        {
            ViewBag.IdRuolo = new SelectList(db.Ruolo, "IdRuolo", "Role");
            return View(new Utente());
        }

        // POST: Utente/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUtente,Nome,Cognome,Provincia,Citta,Indirizzo,Email,Password,IdRuolo")] Utente utente)
        {
            if (ModelState.IsValid)
            {
                bool isDuplicateEmail = db.Utente.Any(u => u.Email == utente.Email && !u.IsDeleted);

                if (isDuplicateEmail)
                {
                    ModelState.AddModelError("Email", "Questo indirizzo email è già utilizzato da un altro utente attivo.");
                    ViewBag.IdRuolo = new SelectList(db.Ruolo, "IdRuolo", "Role", utente.IdRuolo);
                    return View(utente);
                }

                db.Utente.Add(utente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdRuolo = new SelectList(db.Ruolo, "IdRuolo", "Role", utente.IdRuolo);
            return View(utente);
        }

        // GET: Utente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdRuolo = new SelectList(db.Ruolo, "IdRuolo", "Role", utente.IdRuolo);
            return View(utente);
        }

        // POST: Utente/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUtente,Nome,Cognome,Provincia,Citta,Indirizzo,Email,Password,IdRuolo")] Utente utente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdRuolo = new SelectList(db.Ruolo, "IdRuolo", "Role", utente.IdRuolo);
            return View(utente);
        }

        // GET: Utente/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }
            return View(utente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utente utente = db.Utente.Find(id);
            if (utente == null)
            {
                return HttpNotFound();
            }

            try
            {
                utente.IsDeleted = true;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Si è verificato un errore durante la soft delete dell'utente.";
                return View("Error");
            }
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Esercizio_finale_s7/Esercizio_finale_s7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ojuju:wght@200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    <link href="~/Content/Style.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark sticky-top" style="border-bottom: 1px solid black; background-color: #d2d2d2;  ">
        <div class="container">
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    <div class="me-5">
                        <a href="@Url.Action("Home", "Home")" class="navbar-brand m-0"><img src="~/Content/images/logo.png" style="width:100px" /></a>
                        @Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "btn  ms-0" })
                        @Html.ActionLink("Gestione Prodotti", "Index", "Prodotto", new { area = "" }, new { @class = "btn  mx-2" })
                        @Html.ActionLink("Gestione Utenti", "Index", "Utente", new { area = "" }, new { @class = "btn mx-2" })
                        @Html.ActionLink("Gestione Ordini", "Index", "Ordine", new { area = "" }, new { @class = "btn mx-2" })
                    </div>
                    <div class="d-flex">
                        @Html.ActionLink("Carrello", "VisualizzaCarrello", "Home", new { area = "" }, new { @class = "btn me-2" })
                        @Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "btn " })
                    </div>
                }
                else
                {
                    <div class="me-5">
                        <a href="@Url.Action("Home", "Home")" class="navbar-brand m-0"><img src="~/Content/images/logo.png" style="width:100px" /></a>
                        @Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "btn ms-0" })
                    </div>
                    <div class="d-flex">
                        @Html.ActionLink("Carrello", "VisualizzaCarrello", "Home", new { area = "" }, new { @class = "btn me-2" })
                        @Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "btn" })
                    </div>
                }
            }
            else
            {

                <div>
                    <a href="@Url.Action("Home", "Home")" class="navbar-brand"><img src="~/Content/images/logo.png" style="width:100px" /></a>
                    @Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "btn  mx-2" })
                </div>
                @Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "btn mx-2" });
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="mt-5 fixed-bottom customFooter">
        <div class="container p-4" style="height: 13em;">
            <div class="row d-flex justify-content-between" style="height: 100%">
                <div class="col-lg-3 col-md-6 mb-4">
                    <h5 class="mb-3" style="letter-spacing: 2px; color: black;">Dove Siamo</h5>
                    <div class="footer-info" style="color: #4f4f4f;">
                        <p><strong>Indirizzo:</strong> Via della Capanna 1</p>
                        <p><strong>Località:</strong> Roma, RM 00100</p>
                        <p><strong>Telefono:</strong> +39 06XXXXXXX</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 mb-4">
                    <h5 class="mb-3" style="letter-spacing: 2px; color: black; ">Orario di apertura</h5>
                    <div class="footer-info" style="color: #4f4f4f;">
                        <p><strong>Martedì - Domenica:</strong> 19:30 - 23:30</p>
                        <p><strong>Lunedì:</strong> Chiuso</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element)(globalizedValue >= param[0] && globalizedValue <= param[1]);
    }

    $.validator.methods.number = function (value, element) {
        return this.optional(element) /^ -? (?: \d +|\d{ 1, 3 } (?: [\s.,]\d{ 3 }) +) (?: [.,]\d +)?$ /.test(value);
    }
</script>